// @flow
/**
 * An autogenerated component that renders the CDOT iconograpy in SVG.
 *
 * Generated with: convert.js
 */
import * as React from "react";

const Cdot = (props: {|color: string|}): React.Node => {
    return (
        <svg width="48" height="48" xmlns:xlink="http://www.w3.org/1999/xlink">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fill-rule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <g transform="translate(12 12)">
                    <path fill="none" d="M0 0h24v24H0z" />
                    <circle fill={props.color} cx="12" cy="12" r="3" />
                </g>
                <g transform="translate(-118 -518)">
                    <mask id="b" fill="#fff">
                        <use xlinkHref="#a" />
                    </mask>
                    <use fill="#FAFAFA" xlink:href="#a" />
                    <g mask="url(#b)">
                        <path fill="none" d="M118 518h48v48h-48z" />
                        <g transform="translate(130 530)">
                            <path fill="none" d="M0 0h24v24H0z" />
                            <circle fill="#3B3E40" cx="12" cy="12" r="3" />
                        </g>
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Cdot;
