// @flow
/**
 * An autogenerated component that renders the DISMISS iconograpy in SVG.
 *
 * Generated with: convert.js
 */
import * as React from "react";

const Dismiss = (): React.Node => {
    return (
        <svg width="48" height="48" xmlns:xlink="http://www.w3.org/1999/xlink">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fill-rule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path
                    d="m18 21 6 6 6-6"
                    stroke-linecap="round"
                    stroke-width="2"
                    stroke="#71B307"
                    stroke-linejoin="round"
                />
                <g transform="translate(-50 -148)">
                    <mask id="b" fill="#fff">
                        <use xlinkHref="#a" />
                    </mask>
                    <use fill="#FAFAFA" xlink:href="#a" />
                    <g mask="url(#b)">
                        <path fill="none" d="M50 148h48v48H50z" />
                        <path
                            stroke="#71B307"
                            d="m68 169 6 6 6-6"
                            stroke-linecap="round"
                            stroke-width="2"
                            stroke-linejoin="round"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Dismiss;
