// @flow
/**
 * An autogenerated component that renders the LT iconograpy in SVG.
 *
 * Generated with: convert.js
 */
import * as React from "react";

const Lt = (props: {|color: string|}): React.Node => {
    return (
        <svg width="48" height="48" xmlns:xlink="http://www.w3.org/1999/xlink">
            <defs>
                <path id="a" d="M0 0h600v956H0z" />
            </defs>
            <g fill="none" fill-rule="evenodd">
                <path fill="none" d="M0 0h48v48H0z" />
                <path fill="none" d="M12 12h24v24H12z" />
                <path
                    stroke={props.color}
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="m32 30-16-6 16-6"
                />
                <g transform="translate(-366 -586)">
                    <mask id="b" fill="#fff">
                        <use xlinkHref="#a" />
                    </mask>
                    <use fill="#FAFAFA" xlink:href="#a" />
                    <g mask="url(#b)">
                        <path fill="none" d="M366 586h48v48h-48z" />
                        <path fill="none" d="M378 598h24v24h-24z" />
                        <path
                            stroke="#3B3E40"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="m398 616-16-6 16-6"
                        />
                    </g>
                </g>
            </g>
        </svg>
    );
};

export default Lt;
